apiVersion: v1
kind: Pod
metadata:
  name: nvidia-driver
  namespace: openshift-cluster-special-resource-operator
spec:
  restartPolicy: OnFailure
  hostPID: true
  containers:
    - name: nvidia-driver
      image: "quay.io/zvonkok/nvidia-driver:v410.78"
      command: ["nvidia-driver"]
      args: ["init"]
      securityContext:
        privileged: true
      volumeMounts:
        - name: run-nvidia
          mountPath: "/run/nvidia"
          propagation: bidirectional
        - name: hooks
          mountPath: "/etc/containers/oci/hooks.d"
        - name: config
          mountPath: "/etc/containers/oci/hooks.d/oci-nvidia-hook.json"
          subPath: oci-nvidia-hook.json
        - name: host
          mountPath: "/host"
  volumes:
    - name: host
      hostPath:
        path: "/"
    - name: run-nvidia
      hostPath:
        path: "/run/nvidia"
    - name: hooks
      hostPath:
        path: "/etc/containers/oci/hooks.d"
        type: DirectoryOrCreate
    - name: config
      configMap:
        name: nvidia-driver
        items:
          - key: oci-nvidia-hook-json
            path: oci-nvidia-hook.json



