apiVersion: v1
kind: ConfigMap
metadata:
  name: nvidia-driver
data:
  oci-nvidia-hook-json: |
    {
        "version": "1.0.0",
        "hook": {
            "path": "/usr/libexec/oci/hooks.d/oci-nvidia-hook",
            "args": ["oci-nvidia-hook", "prestart"],
            "env": [
                "PATH=/run/nvidia/driver/usr/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin"
            ]
        },
        "when": {
            "always": true,
            "commands": [".*"]
        },
        "stages": ["prestart"]
    }
