apiVersion: v1
kind: Pod
metadata:
  name: nvidia-driver
  namespace: openshift-cluster-special-resource-operator
spec:
  restartPolicy: OnFailure
  hostPID: true
  containers:
    - name: nvidia-driver
      image: "quay.io/zvonkok/nvidia-driver:v410.78"
      command: ["nvidia-driver"]
      args: ["init"]
      securityContext:
        privileged: true
        seLinuxOptions:
          level: "s0"
      volumeMounts:
        - name: run-nvidia
          mountPath: /run/nvidia
          mountPropagation: Bidirectional
        - name: config
          mountPath: /etc/containers/oci/hooks.d
        - name: host
          mountPath: /host
  volumes:
    - name: host
      hostPath:
        path: /
    - name: run-nvidia
      hostPath:
        path: /run/nvidia
    - name: config
      configMap:
        name: nvidia-driver
        items:
          - key: oci-nvidia-hook-json
            path: oci-nvidia-hook.json
  nodeSelector:
    node.alpha.kubernetes-incubator.io/nfd-pci-0300_10de.present: "true" 


